spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projectssere@gmail.com
spring.mail.password=llbkvwatbuxypbxs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

mylocker.admin.email=projectssere@gmail.com
mylocker.admin.username=boika
mylocker.admin.password=Locker@2026
mylocker.admin.email-login=projectssere@gmail.com
mylocker.demo.email=demo@hopeconnect.dev
mylocker.demo.password=Demo1234!

spring.datasource.url=jdbc:postgresql://localhost:5432/lockerdb
spring.datasource.username=postgres
spring.datasource.password=Newlands@12345
mylocker.resend.api-key=re_AHXVYnfg_PyjrB8aY9w5q8YQCcYaSsmvY
mylocker.resend.from=HopeConnect <onboarding@resend.dev>